services:

  selenium:
    image: adhan_home
    environment:
      - TZ=${TZ}
    build:
      context: .
      dockerfile: docker/dockerfile
      args:
        - CURRENT_USER=${CURRENT_USER}
        - CURRENT_UID=${CURRENT_UID}
    container_name: ${CONTAINER_NAME_ADHAN:-adhan-home}
    env_file: .env
    restart: always
    # volumes:
    #   - ./:/var/www/html
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - VOLUME_HOME_ASSISTANT:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host
    #For use Zigbee
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

  owntone:
    container_name: owntone
    image: owntone/owntone:latest
    network_mode: host
    environment:
      - UID=${CURRENT_UID:-1000}
      - GID=${CURRENT_GID:-1000}
    volumes:
      - "${HOME}/OwnTone/etc:/etc/owntone"
      - "${HOME}/OwnTone/media:/srv/media"
      - "${HOME}/OwnTone/cache:/var/cache/owntone"
    restart: unless-stopped

volumes:
  VOLUME_HOME_ASSISTANT:
  VOLUME_OWNTONE: