version: "3.9"

services:

  selenium:
    image: adhan_home
    environment:
      - TZ=${TZ}
    build:
      context: .
      dockerfile: docker/dockerfile
      args:
        - CURRENT_USER=${CURRENT_USER}
        - CURRENT_UID=${CURRENT_UID}
    container_name: ${CONTAINER_NAME_ADHAN:-adhan-home}
    env_file: .env
    restart: always

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - VOLUME_HOME_ASSISTANT:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: always
    privileged: true
    network_mode: host
    #For use Zigbee
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
  
volumes:
  VOLUME_HOME_ASSISTANT: